port: "8080"
routes:
  - name: order
    prefix: /api/v1/order
    destination: http://localhost:8040/v1/order
    authentication: key
    ratelimit:
      requests: 5
      timeframe: hour
      type: ip
  - name: catalog
    prefix: /api/v1/catalog
    destination: http://localhost:8080/catalog/items
    authentication: none
    ratelimit:
      requests: 15
      timeframe: minute
      type: ip